
name: test

on: [push]
jobs:

  startVM:
    runs-on: ubuntu-latest
    steps:
    
    #Test again
    - name: Login to AZ CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run:
          az vm start -g ${{ secrets.AZURE_RESSOURCE }} -n ${{ secrets.AZURE_VM }}

  pythonCode:
    runs-on: self-hosted
    needs: startVM
    steps:
    
    - uses: actions/checkout@v2
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: SymphoniaLauren/Tales-of-Rebirth
        
    - name: Extract DAT.bin
      working-directory: ./PythonLib
      run:
        python ./PytthonLib/ToolsTales_Executable.py --game TOR unpack Main
        
  closeVM:
    runs-on: ubuntu-latest
    needs: pythonCode
    steps:

    - name: Login to AZ CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run:
          az vm stop -g ${{ secrets.AZURE_RESSOURCE }} -n ${{ secrets.AZURE_VM }}
        
    
    
